// Autogenerated Scheme to C++ Code
// File: 01P2.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main(){
	round(Object(2.2));
	Object(1) % Object(2);
	Object(1)* Object(2);
	if(Object(1)> Object(-5)){
		cout << "1 is greater";
	}
	else{
		Object(2);
	}
	cout << endl;
	return 0;
}
