// Autogenerated Scheme to C++ Code
// File: mytest.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main(){
	cout << 	round();
(Object(3)moduloObject(7));
	cout << endl;
	return 0;
}
