// Autogenerated Scheme to C++ Code
// File: test.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object myFUNC(Object p1, Object p2, Object p3){
	if(p1 > p2){
		cout << ":)\n";
	}
	else{
		Object(2);
	}
	return 0;
}
int main(){
	if(Object(3) > Object(3)){ 
		Object(greater);
	}
	else if(	Object(3) < Object(3)){ 
"less";
	}
	else{
 "equal";
	}
	return 0;
}
