// Autogenerated Scheme to C++ Code
// File: wattstest7.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object iftest(Object a, Object b, Object c){
	return Object(	if(		;
 && 	;
;
){
	"all_the_same ";
;
	}
	else{
			if(	 >  ||  > ;
){
	"in_ascending_order ";
;
	}
	else{
			if(	 < ){
	"in_decscending_order ";
;
	}
	else{
		"three_values_passed";
;
	}
;
	}
;
	}
Object(a)Object(b)Object(b)Object(c)Object(a)Object(b)Object(b)Object(c)Object(a)Object(c);
);
}
int main(){
	cout << iftest(Object(10)Object(15)Object(20);
	cout << endl;
	cout << iftest(Object(10)Object(10)Object(10);
	cout << endl;
	cout << iftest(Object(20)Object(15)Object(10);
	cout << endl;
	cout << iftest(Object(15)Object(10)Object(20);
	cout << endl;
	return 0;
}
