// Autogenerated Scheme to C++ Code
// File: wattstest2.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main(){
	cout << ;
	cout << endl;
	cout << ;
;
(/-Object(1.4));
;
	cout << endl;
	cout << ;
	cout << endl;
	cout << (Object(-6)Object(5)Object(7));
	cout << endl;
	cout << 	round();
;
	cout << endl;
	return 0;
}
