// Autogenerated Scheme to C++ Code
// File: wattstest6.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object predicates(Object x){
	return Object(	if(	stringp()){
	;
	}
	else{
			if(	nullp()){
	;
	}
	else{
			if(	listp()){
	;
	}
	else{
			if(	zerop()){
	;
	}
	else{
			if(	numberp()){
	;
	}
	else{
		;
	}
;
	}
;
	}
;
	}
;
	}
Object(x)Object("Is a string")Object(x)Object("Is null")Object(x)Object("Is a list")Object(x)Object("Is zero")Object(x)Object("Is a number")Object("Is a USO");
);
}
int main(){
	cout << predicates(Object(0);
	cout << endl;
	cout << predicates((Object(5)+Object(6))	cout << endl;
	cout << predicates("(a b c)";
	cout << endl;
	cout << predicates("()";
	cout << endl;
	cout << predicates(Object("hello world");
	cout << endl;
	return 0;
}
