// Autogenerated Scheme to C++ Code
// File: wattstest1.cpp
#include <iostream>
#include "Object.h"
using namespace std;

int main(){
	cout << Object(5678);
	cout << endl;
	cout << Object(3.14159);
	cout << endl;
	cout << "x";
	cout << endl;
	cout << "xyz";
	cout << endl;
	cout << "Sonoma State";
	cout << endl;
	cout << "(1 23 abc de45)";
	cout << endl;
	return 0;
}
