// Autogenerated Scheme to C++ Code
// File: wattstest5.cpp
#include <iostream>
#include "Object.h"
using namespace std;

Object abs1(Object v){
	return Object(	if( > ){
	;
	}
	else{
		;
	}
Object(v)-Object(0)-Object(v)-(Object(0)-Object(v));
);
}
Object abs2(Object v){
	return Object(	if(	numberp()){
		if( > ){
	;
	}
	else{
		;
	}
;
	}
	else{
		"NotNumeric";
;
	}
Object(v)-Object(v)-Object(0)-Object(v)-(Object(0)-Object(v));
);
}
int main(){
	cout << abs1(Object(-5);
	cout << endl;
	cout << abs1(Object(15);
	cout << endl;
	cout << abs2(Object(-25);
	cout << endl;
	cout << abs2(Object(35);
	cout << endl;
	cout << abs2("x";
	cout << endl;
	return 0;
}
